// Code generated by goctl. DO NOT EDIT.
package types

type BookMsg struct {
	Number string `json:"number"`
	Name   string `json:"name"`
	Count  int    `json:"count"`
}

type BookSet struct {
	BookMsgs []*BookMsg `json:"bookMsgs"`
}

type Msg struct {
	Name    string `json:"name"`
	Gender  string `json:"gender"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
	Address string `json:"address"`
}

type PeopleMsg struct {
	People []*Msg `json:"people"`
}

type Count struct {
	Num int64 `json:"num"`
}

type BookName struct {
	Name string `json:"name"`
}

type BookID struct {
	Id string `json:"id"`
}
