// Code generated by goctl. DO NOT EDIT.
package types

type UserLogin struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type JWT struct {
	Token string `json:"token"`
}

type UserMsg struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Phone    string `josn:"phone"`
	Address  string `json:"address"`
	Email    string `json:"email"`
}
