// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"go-zero-easy/service/user/cmd/rpc/internal/logic"
	"go-zero-easy/service/user/cmd/rpc/internal/svc"
	"go-zero-easy/service/user/cmd/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserMsg(ctx context.Context, in *user.UserId) (*user.UserMsg, error) {
	l := logic.NewGetUserMsgLogic(ctx, s.svcCtx)
	return l.GetUserMsg(in)
}

func (s *UserServer) GetSomeUserMsg(stream user.User_GetSomeUserMsgServer) error {
	l := logic.NewGetSomeUserMsgLogic(stream.Context(), s.svcCtx)
	return l.GetSomeUserMsg(stream)
}
