// Code generated by goctl. DO NOT EDIT.
package handler

import (
	participate2 "go-zero-easy/service/user/cmd/api/internal/handler/participate"
	"go-zero-easy/service/user/cmd/api/internal/svc"
	"net/http"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/modify",
				Handler: participate2.ModifyInformationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/show",
				Handler: participate2.ShowMsgHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
