// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Members "go-zero-easy/service/search/cmd/api/internal/handler/Members"
	"go-zero-easy/service/search/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search/book/:name",
				Handler: SearchBookHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search/get/book/:bookid",
				Handler: Members.GetBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/return/book/:bookid",
				Handler: Members.ReturnBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/view/book",
				Handler: Members.ViewBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/viewmsg/book/:bookid",
				Handler: Members.ViewWhoMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/viewhow/book",
				Handler: Members.ViewHowBookHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
